import test from 'node:test'; import assert from 'node:assert/strict';
import { isUuid, validateMedia, signatureValid, classify, validContent } from './validation.mjs';
const uid='550e8400-e29b-41d4-a716-446655440000', up='550e8400-e29b-41d4-a716-446655440001', id='550e8400-e29b-41d4-a716-446655440002';
const media=(ext='jpg',mime='image/jpeg',media_id=id,storage_path=`tmp/${uid}/${up}/${media_id}.${ext}`,byte_size=1)=>({media_id,storage_path,mime_type:mime,byte_size});
test('canonical image paths and MIME bindings',()=>{assert.ok(validateMedia({uid,uploadId:up,media:[media()]}));assert.ok(validateMedia({uid,uploadId:up,media:[media('png','image/png')]}));assert.ok(validateMedia({uid,uploadId:up,media:[media('webp','image/webp')]}));assert.equal(validateMedia({uid,uploadId:up,media:[media('png','image/jpeg')]}),false);assert.equal(validateMedia({uid,uploadId:up,media:[media('mp4','video/mp4')]}),false)});
test('path, UUID, and duplicate rejection',()=>{assert.ok(isUuid(up));assert.equal(isUuid('bad'),false);assert.equal(validateMedia({uid,uploadId:up,media:[media('jpg','image/jpeg',id,`tmp/x/${up}/${id}.jpg`)]}),false);assert.equal(validateMedia({uid,uploadId:up,media:[media('jpg','image/jpeg',id,`tmp/${uid}/${up}/x/${id}.jpg`)]}),false);assert.equal(validateMedia({uid,uploadId:up,media:[media(),media()]}),false);assert.equal(validateMedia({uid,uploadId:up,media:[media(),media('png','image/png')]}),false)});
test('count and size limits',()=>{assert.ok(validateMedia({uid,uploadId:up,media:[]}));assert.equal(validateMedia({uid,uploadId:up,media:Array.from({length:6},(_,i)=>media('jpg','image/jpeg',`550e8400-e29b-41d4-a716-44665544000${i}`,`tmp/${uid}/${up}/550e8400-e29b-41d4-a716-44665544000${i}.jpg`))}),false);assert.ok(validateMedia({uid,uploadId:up,media:[media('jpg','image/jpeg',id,undefined,5242880)]}));assert.equal(validateMedia({uid,uploadId:up,media:[media('jpg','image/jpeg',id,undefined,5242881)]}),false)});
test('signatures',()=>{assert.ok(signatureValid('image/jpeg',new Uint8Array([255,216,255])));assert.ok(signatureValid('image/png',new Uint8Array([137,80,78,71,13,10,26,10])));assert.ok(signatureValid('image/webp',new Uint8Array([...Buffer.from('RIFFxxxxWEBP')] )));assert.equal(signatureValid('image/jpeg',new Uint8Array([0])),false)});
test('roles and content',()=>{assert.deepEqual(classify('client','Grocery','Offer'),{ok:true,category:null,postType:null});assert.ok(classify('seller','Grocery','Offer').ok);assert.equal(classify('seller','Bad','Offer').ok,false);assert.equal(classify(null,null,null).ok,false);assert.ok(validContent('text'));assert.equal(validContent(' '),false)});
