import React from 'react';
import BarcodeSVG from './BarcodeSVG';
import { formatPrice } from '@/lib/utils';

export default function BarcodeLabelPreview({ labels, sizePreset, symbology, toggles }) {
  
  const getScale = () => {
    if (sizePreset.width >= 80) return { name: '13px', sku: '10px', price: '14px', bcHeight: 45, bcWidth: 1.5 };
    if (sizePreset.width >= 50) return { name: '12px', sku: '9px', price: '12px', bcHeight: 35, bcWidth: 1.3 };
    if (sizePreset.width >= 35) return { name: '10px', sku: '8px', price: '11px', bcHeight: 30, bcWidth: 1.0 };
    return { name: '9px', sku: '7px', price: '9px', bcHeight: 25, bcWidth: 0.8 };
  };

  const scale = getScale();

  return (
    <div className="print-area flex flex-col items-center gap-6 w-full bg-slate-100 pb-10 print:bg-white print:pb-0 print:gap-0">
      {labels.map((label, idx) => (
        <div 
          key={idx} 
          className="label-page relative bg-white border border-slate-200 shadow-sm mx-auto rounded-md"
          style={{
             width: `${sizePreset.width}mm`,
             height: `${sizePreset.height}mm`,
          }}
        >
          {label.isAutoGenerated && (
            <div className="no-print absolute top-0 right-0 bg-blue-500 text-white text-[8px] px-1.5 py-0.5 rounded-bl shadow-sm opacity-90" title="Auto-Generated Barcode">
              Auto
            </div>
          )}

          <div className="label-content w-full h-full flex flex-col justify-between items-center box-border p-[1mm]">
             <div className="flex flex-col items-center justify-start w-full text-center overflow-hidden">
               {toggles?.showName && (
                 <div className="font-bold text-slate-800 print:text-black w-full" 
                      style={{ 
                        fontSize: scale.name, 
                        lineHeight: '1.1',
                        maxHeight: '2.2em', 
                        overflow: 'hidden', 
                        textOverflow: 'ellipsis',
                        display: '-webkit-box', 
                        WebkitLineClamp: 2, 
                        WebkitBoxOrient: 'vertical',
                        margin: '0 0 0.5mm 0'
                      }}>
                    {label.name}
                 </div>
               )}
               
               {toggles?.showSKU && label.sku && (
                 <div className="text-slate-600 print:text-black font-medium text-center" 
                      style={{ 
                        fontSize: scale.sku, 
                        lineHeight: '1',
                        margin: '0 0 0.5mm 0'
                      }}>
                   SKU: {label.sku}
                 </div>
               )}
               
               {toggles?.showPrice && (
                 <div className="font-extrabold text-slate-900 print:text-black text-center" 
                      style={{ 
                        fontSize: scale.price,
                        lineHeight: '1',
                        margin: '0 0 0.5mm 0'
                      }}>
                    {formatPrice(label.price)}
                 </div>
               )}
             </div>
             
             <div className="w-full flex justify-center items-end overflow-hidden">
                <BarcodeSVG 
                    value={label.barcode} 
                    format={symbology} 
                    height={scale.bcHeight} 
                    width={scale.bcWidth}
                    displayValue={true} 
                />
             </div>
          </div>
        </div>
      ))}
    </div>
  );
}