import React from 'react';
import { Helmet } from 'react-helmet-async';
import { motion } from 'framer-motion';

const PrivacyPolicyPage = () => {
  const sections = [
    {
      title: "1. Information We Collect",
      content: "We collect information you provide directly to us (e.g., business details, contact info) and data generated by your use of our platform (e.g., order history, inventory data). As a B2B marketplace, we also process business verification documents."
    },
    {
      title: "2. How We Use Your Information",
      content: "We use your data to facilitate B2B transactions, manage subscriptions, and improve our software tools. Supplier contact information is shared with retailers for order fulfillment purposes."
    },
    {
      title: "3. Marketplace Data Sharing",
      content: "As a facilitator, we share necessary order details (Retailer Name, Address, Order Items) with the respective Wholesaler to enable fulfillment. We do not sell your data to external advertisers."
    },
    {
      title: "4. Payment Data",
      content: "We do not store complete credit card details. Online payments for subscriptions are processed by secure third-party gateways. Product payments are Cash on Delivery and do not involve online processing of sensitive financial data for those transactions."
    },
    {
      title: "5. Data Security",
      content: "We employ enterprise-grade security to protect your business data, inventory records, and customer lists stored on our POS system."
    }
  ];

  return (
    <div className="bg-slate-50 min-h-screen">
      <Helmet>
        <title>ShopoApp | Smart POS Billing, Inventory & Taxation Software</title>
        <meta name="description" content="Learn how ShopoApp protects your business data, inventory records, and customer information with enterprise-grade security." />
      </Helmet>

      <main className="container mx-auto px-4 py-16">
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="text-center mb-12"
        >
          <h1 className="text-5xl md:text-6xl font-bold gradient-text mb-4">Privacy Policy</h1>
          <p className="text-base text-slate-500 max-w-3xl mx-auto mt-4">
            ShopoApp is operated by <span className="font-semibold text-slate-700">Ninety Layers Enterprises</span>. We value the privacy of our wholesale and retail partners.
          </p>
        </motion.div>

        <div className="max-w-4xl mx-auto bg-white p-8 md:p-12 rounded-lg shadow-lg">
          <div className="prose prose-lg max-w-none text-slate-700">
            {sections.map((section, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                className="mb-8"
              >
                <h2 className="text-2xl font-bold text-slate-800 mb-3">{section.title}</h2>
                <p>{section.content}</p>
              </motion.div>
            ))}
            <div className="mt-12 border-t pt-8">
              <h2 className="text-2xl font-bold text-slate-800 mb-3">Contact Us</h2>
              <p>For data privacy queries: <a href="mailto:info@shopoapp.com" className="text-blue-600 hover:underline">info@shopoapp.com</a>.</p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default PrivacyPolicyPage;